# Generated by Django 3.1.1 on 2020-11-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201018_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
