# Generated by Django 3.1.1 on 2020-11-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_template_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
