# Generated by Django 3.1.1 on 2020-11-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201111_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='issues',
            field=models.ManyToManyField(to='mainapp.Tags'),
        ),
    ]
