# Generated by Django 3.1.1 on 2020-11-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20201111_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
