# Generated by Django 3.1.1 on 2020-11-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_template_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_submittedForReview',
            field=models.BooleanField(default=False),
        ),
    ]
