# Generated by Django 3.1.1 on 2020-11-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_myuser_issues'),
        ('mainapp', '0008_template_is_submittedforreview'),
    ]

    operations = [
    ]
